
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['192.168.57.3:9093']



rule_files:
  - "first_rules.yml"    





scrape_configs:
  - job_name: node
    scrape_interval: 5s
    static_configs:
     - targets: ['192.168.57.3:9100','192.168.57.2:9100']
  - job_name: 'cAdvisor' 
    static_configs:
     - targets: ['192.168.57.3:8080']


  - job_name: dockermetrics
    static_configs:
      - targets: ['192.168.57.3:9417']      



  - job_name: blackbox
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://vesti.ru
        - https://lms.skillfactory.ru  
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 0.0.0.0:9115
